name        : libgsf
version     : 1.14.33
release     : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgsf/1.14/libgsf-1.14.33.tar.xz : 82dd38e0c1f497704bf3b43682fca2768886058f004b14e9b5d103596f8c6e6b
license     : LGPL-2.1
summary     : Library providing I/O for structured file formats
builddeps   :
    - pkgconfig(libxml-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - intltool
description : |
    libgsf contains the lbrary used for providing an extensible input/output abstraction layer for structure file formats within GNOME.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
