name       : libgsf
version    : 1.14.48
release    : 8
source     :
    - https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.48.tar.xz : ff86d7f1d46dd0ebefb7bd830a74a41db64362b987bf8853fff6ab4c1132b837
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library providing I/O for structured file formats
description: |
    libgsf contains the library used for providing an extensible input/output abstraction layer for structured file formats within GNOME.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - bzip2-devel
    - intltool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
