name       : libgsf
version    : 1.14.44
release    : 5
source     :
    - https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.44.tar.xz : 68bede10037164764992970b4cb57cd6add6986a846d04657af9d5fac774ffde
license    : LGPL-2.1
component  : desktop.library
summary    : Library providing I/O for structured file formats
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - bzip2-devel
    - intltool
description: |
    libgsf contains the lbrary used for providing an extensible input/output abstraction layer for structure file formats within GNOME.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
