name       : libgsf
version    : 1.14.47
release    : 7
source     :
    - https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.47.tar.xz : d188ebd3787b5375a8fd38ee6f761a2007de5e98fa0cf5623f271daa67ba774d
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library providing I/O for structured file formats
description: |
    libgsf contains the lbrary used for providing an extensible input/output abstraction layer for structure file formats within GNOME.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - bzip2-devel
    - intltool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
