name       : libgsf
version    : 1.14.49
release    : 9
source     :
    - https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.49.tar.xz : e9ebe36688f010c9e6e40c8903f3732948deb8aca032578d07d0751bd82cf857
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library providing I/O for structured file formats
description: |
    libgsf contains the library used for providing an extensible input/output abstraction layer for structured file formats within GNOME.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - bzip2-devel
    - intltool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
